version: '3.13'
services:
services:
  my_cassandra:
    image: cassandra:latest
jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work